/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _MOZILLA_CONFIG_H_
#define _MOZILLA_CONFIG_H_

#define ACCESSIBILITY 1
#define ANDROID 1
#define ANDROID_VERSION 5
#define ATTRIBUTE_ALIGNED_MAX 64
#define BUILD_CTYPES 1
#define CROSS_COMPILE 1
#define D_INO d_ino
#define ENABLE_SYSTEM_EXTENSION_DIRS 1
#define FIREFOX_VERSION 17.0a1
#define HAVE_ARM_NEON 1
#define HAVE_ARM_SIMD 1
#define HAVE_CLOCK_MONOTONIC 1
#define HAVE_DIRENT_H 1
#define HAVE_DLOPEN 1
#define HAVE_FCHMOD 1
#define HAVE_FLOCKFILE 1
#define HAVE_FT_BITMAP_SIZE_Y_PPEM 1
#define HAVE_FT_GLYPHSLOT_EMBOLDEN 1
#define HAVE_FT_LOAD_SFNT_TABLE 1
#define HAVE_GETOPT_H 1
#define HAVE_I18N_LC_MESSAGES 1
#define HAVE_INTTYPES_H 1
#define HAVE_ISATTY 1
#define HAVE_LCHOWN 1
#define HAVE_LINUX_QUOTA_H 1
#define HAVE_LOCALTIME_R 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define HAVE_MEMMEM 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_MMINTRIN_H 1
#define HAVE_RINT 1
#define HAVE_SETBUF 1
#define HAVE_SIGINFO_T 1
#define HAVE_SNPRINTF 1
#define HAVE_SSIZE_T 1
#define HAVE_STDINT_H 1
#define HAVE_STRERROR 1
#define HAVE_STRNDUP 1
#define HAVE_STRTOK_R 1
#define HAVE_ST_BLKSIZE 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_SYS_STATFS_H 1
#define HAVE_SYS_SYSMACROS_H 1
#define HAVE_UINT 1
#define HAVE_UINT64_T 1
#define HAVE_UINT_T 1
#define HAVE_UNAME_DOMAINNAME_FIELD 1
#define HAVE_UNISTD_H 1
#define HAVE_VALLOC 1
#define HAVE_VISIBILITY_ATTRIBUTE 1
#define HAVE_VISIBILITY_HIDDEN_ATTRIBUTE 1
#define HAVE__UNWIND_BACKTRACE 1
#define IBMBIDI 1
#define JSGC_INCREMENTAL 1
#define JS_DEFAULT_JITREPORT_GRANULARITY 3
#define LIBJPEG_TURBO_ARM_ASM 1
#define MALLOC_H <malloc.h>
#define MOZILLA_UAVERSION "17.0"
#define MOZILLA_VERSION "17.0a1"
#define MOZILLA_VERSION_U 17.0a1
#define MOZ_ANDROID_HISTORY 1
#define MOZ_APP_COMPONENT_INCLUDE "nsBrowserComponents.h"
#define MOZ_APP_UA_NAME "Firefox"
#define MOZ_APP_UA_VERSION "17.0a1"
#define MOZ_BUILD_APP mobile/android
#define MOZ_CRASHREPORTER 1
#define MOZ_CRASHREPORTER_ENABLE_PERCENT 100
#define MOZ_DEBUG_SYMBOLS 1
#define MOZ_DISABLE_DOMCRYPTO 1
#define MOZ_DISTRIBUTION_ID "org.mozilla"
#define MOZ_DLL_SUFFIX ".so"
#define MOZ_ENABLE_PROFILER_SPS 1
#define MOZ_ENABLE_SKIA 1
#define MOZ_FEEDS 1
#define MOZ_GFX_OPTIMIZE_MOBILE 1
#define MOZ_GRAPHITE 1
#define MOZ_INSTRUMENT_EVENT_LOOP 1
#define MOZ_JAVA_COMPOSITOR 1
#define MOZ_LINKER 1
#define MOZ_LOGGING 1
#define MOZ_MACBUNDLE_ID org.mozilla.fennec tag
#define MOZ_MEDIA 1
#define MOZ_MEDIA_NAVIGATOR 1
#define MOZ_MEMORY 1
#define MOZ_MEMORY_ANDROID 1
#define MOZ_MEMORY_LINUX 1
#define MOZ_MEMORY_SIZEOF_PTR_2POW 2
#define MOZ_OGG 1
#define MOZ_OMNIJAR 1
#define MOZ_OPUS 1
#define MOZ_PDF_PRINTING 1
#define MOZ_PLACES 1
#define MOZ_PROFILELOCKING 1
#define MOZ_RAW 1
#define MOZ_SPEEX_RESAMPLER 1
#define MOZ_STATIC_JS 1
#define MOZ_SYDNEYAUDIO 1
#define MOZ_THUMB2 1
#define MOZ_TREE_CAIRO 1
#define MOZ_TREE_FREETYPE 1
#define MOZ_TREE_PIXMAN 1
#define MOZ_TREMOR 1
#define MOZ_UPDATE_CHANNEL default
#define MOZ_USER_DIR ".mozilla"
#define MOZ_USE_NATIVE_POPUP_WINDOWS 1
#define MOZ_VP8 1
#define MOZ_WAVE 1
#define MOZ_WEBM 1
#define MOZ_WIDGET_ANDROID 1
#define MOZ_XTF 1
#define MOZ_XUL 1
#define NO_PW_GECOS 1
#define NO_X11 1
#define NS_ALWAYS_INLINE __attribute__((always_inline))
#define NS_ATTR_MALLOC __attribute__((malloc))
#define NS_PRINTING 1
#define NS_PRINT_PREVIEW 1
#define NS_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#define SIZEOF_INT_P 4
#define STDC_HEADERS 1
#define UNIX_ASYNC_DNS 1
#define USE_ARM_KUSER 1
#define VPX_ARM_ASM 1
#define XP_UNIX 1
#define X_DISPLAY_MISSING 1

/* The c99 defining the limit macros (UINT32_MAX for example), says:
 * C++ implementations should define these macros only when __STDC_LIMIT_MACROS
 * is defined before <stdint.h> is included. */
#define __STDC_LIMIT_MACROS

/* Force-include hunspell_alloc_hooks.h for hunspell, so that we don't need to
 * modify it directly.
 *
 * HUNSPELL_STATIC is defined in extensions/spellcheck/hunspell/src/Makefile.in,
 * unless --enable-system-hunspell is defined.
 */
#if defined(HUNSPELL_STATIC)
#include "hunspell_alloc_hooks.h"
#endif

#endif /* _MOZILLA_CONFIG_H_ */

